apiVersion: v1
kind: Service
metadata:
  name: {{ include "flutterdb.fullname" . }}
  labels:
    {{- include "flutterdb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiService.type }}
  ports:
    - port: {{ .Values.apiService.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "flutterdb.selectorLabels" . | nindent 4 }}
